# Generated by Django 5.2.6 on 2025-09-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='resolved',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('water', 'Water Quality'), ('disease', 'Predicted Disease')], default='water', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(default='unresolved', max_length=20),
        ),
    ]
